import { Alegreya_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./Components/Nav";
import LandingGradient from "./Components/LandingGradient";

const alegreyaSans = Alegreya_Sans({
	subsets: ["latin"],
	weight: ["100", "300", "400", "500", "700", "800", "900"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${alegreyaSans.variable} antialiased`}>
				<Nav />

				{children}
			</body>
		</html>
	);
}
